name: Build LaTeX and deploy on GitHub Releases
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  setup-compile-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install TeX Live
        run: sudo apt-get install -y texlive-full
        
      - name: Add TeX Live to PATH
        run: echo "/usr/local/texlive/2023/bin/x86_64-linux" >> $GITHUB_PATH
      
      - name: Install Inkscape
        run: sudo apt-get install -y inkscape

      - name: Compile LaTeX document
        run: pdflatex --shell-escape -synctex=1 \\nonstopmode \\input{thesis-main.tex}
